//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Optics.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medical_Optics.Application.Common.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code not found.
        /// </summary>
        public static string AccountCodeNotFound {
            get {
                return ResourceManager.GetString("AccountCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All voucher must be posted before closing financial period.
        /// </summary>
        public static string AllVoucherMustBePosted {
            get {
                return ResourceManager.GetString("AllVoucherMustBePosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charachters only.
        /// </summary>
        public static string CharachtersOnly {
            get {
                return ResourceManager.GetString("CharachtersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose account.
        /// </summary>
        public static string ChooseAccount {
            get {
                return ResourceManager.GetString("ChooseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose account or costcenter.
        /// </summary>
        public static string ChooseAccountOrCostCenter {
            get {
                return ResourceManager.GetString("ChooseAccountOrCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose costcenter.
        /// </summary>
        public static string ChooseCostCenter {
            get {
                return ResourceManager.GetString("ChooseCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date in current financial period.
        /// </summary>
        public static string ChooseDateInCurrenetFinanicalPeriod {
            get {
                return ResourceManager.GetString("ChooseDateInCurrenetFinanicalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exist.
        /// </summary>
        public static string CodeAlreadyExist {
            get {
                return ResourceManager.GetString("CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code example.
        /// </summary>
        public static string CodeExample {
            get {
                return ResourceManager.GetString("CodeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company branch not exist.
        /// </summary>
        public static string CompanyBranchNotExist {
            get {
                return ResourceManager.GetString("CompanyBranchNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costcenter code not Found.
        /// </summary>
        public static string CostCenterCodeNotFound {
            get {
                return ResourceManager.GetString("CostCenterCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete data.
        /// </summary>
        public static string DataNotCompleted {
            get {
                return ResourceManager.GetString("DataNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Required.
        /// </summary>
        public static string DebitRequired {
            get {
                return ResourceManager.GetString("DebitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number like the example ###.##.
        /// </summary>
        public static string DecimalNotValid {
            get {
                return ResourceManager.GetString("DecimalNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error , Please contact Technical support.
        /// </summary>
        public static string DefaultErrorMessage {
            get {
                return ResourceManager.GetString("DefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exist.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email like the example :  username@example.com..
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number of repeted ,or repeate end date.
        /// </summary>
        public static string EndDateAndNumberOfRecurrenceNotExist {
            get {
                return ResourceManager.GetString("EndDateAndNumberOfRecurrenceNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ,Please try again.
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter total for number of days.
        /// </summary>
        public static string EveryNumberOfDaysNotExist {
            get {
                return ResourceManager.GetString("EveryNumberOfDaysNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter freezing reason.
        /// </summary>
        public static string FreezingReasonMsg {
            get {
                return ResourceManager.GetString("FreezingReasonMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be between 0 - 100  ###.##.
        /// </summary>
        public static string fromzeroto100 {
            get {
                return ResourceManager.GetString("fromzeroto100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered date can&apos;t be bigger than current date.
        /// </summary>
        public static string FutureDateNotAllowed {
            get {
                return ResourceManager.GetString("FutureDateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select voucher type.
        /// </summary>
        public static string GlJournalVoucherCategoryNotExist {
            get {
                return ResourceManager.GetString("GlJournalVoucherCategoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least on row.
        /// </summary>
        public static string GridLengthZero {
            get {
                return ResourceManager.GetString("GridLengthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least on row.
        /// </summary>
        public static string GridLengthZeroChoose {
            get {
                return ResourceManager.GetString("GridLengthZeroChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Fax.
        /// </summary>
        public static string InvalidFax {
            get {
                return ResourceManager.GetString("InvalidFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length between 10-15.
        /// </summary>
        public static string InvalidFaxLength {
            get {
                return ResourceManager.GetString("InvalidFaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Identification Number.
        /// </summary>
        public static string InvalidIdentificationNumber {
            get {
                return ResourceManager.GetString("InvalidIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length between 10-20.
        /// </summary>
        public static string InvalidIdentificationNumberLength {
            get {
                return ResourceManager.GetString("InvalidIdentificationNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Image.
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile Number.
        /// </summary>
        public static string InvalidMobile {
            get {
                return ResourceManager.GetString("InvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length between 10-15.
        /// </summary>
        public static string InvalidMobileLength {
            get {
                return ResourceManager.GetString("InvalidMobileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length between 10-15.
        /// </summary>
        public static string InvalidPhoneLength {
            get {
                return ResourceManager.GetString("InvalidPhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Not Valid.
        /// </summary>
        public static string LinkNotValid {
            get {
                return ResourceManager.GetString("LinkNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Not Valid.
        /// </summary>
        public static string MailNotValid {
            get {
                return ResourceManager.GetString("MailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Allowed File Size 10 mb.
        /// </summary>
        public static string MaxAllowedFileSizeMsg {
            get {
                return ResourceManager.GetString("MaxAllowedFileSizeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number like the example ###.##.
        /// </summary>
        public static string MaxAllowedMargin {
            get {
                return ResourceManager.GetString("MaxAllowedMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 1000 character.
        /// </summary>
        public static string MaxLength1000NotValid {
            get {
                return ResourceManager.GetString("MaxLength1000NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 50 character.
        /// </summary>
        public static string MaxLength50NotValid {
            get {
                return ResourceManager.GetString("MaxLength50NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 100 character.
        /// </summary>
        public static string MaxLengthNotValid {
            get {
                return ResourceManager.GetString("MaxLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length is 6 character.
        /// </summary>
        public static string MinLengthNotValid {
            get {
                return ResourceManager.GetString("MinLengthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustadd financial period first.
        /// </summary>
        public static string MustAddFinancialPeriodFirst {
            get {
                return ResourceManager.GetString("MustAddFinancialPeriodFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative not allowed.
        /// </summary>
        public static string NegativeQty {
            get {
                return ResourceManager.GetString("NegativeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ,No coding created.
        /// </summary>
        public static string NoCodingCreated {
            get {
                return ResourceManager.GetString("NoCodingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to register employee before you can create user.
        /// </summary>
        public static string NoEmployeeAvailable {
            get {
                return ResourceManager.GetString("NoEmployeeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        public static string NoFileSelectedMsg {
            get {
                return ResourceManager.GetString("NoFileSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allowed Date.
        /// </summary>
        public static string NotAllowedDate {
            get {
                return ResourceManager.GetString("NotAllowedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter notification dates.
        /// </summary>
        public static string NotificationPeriodNotExist {
            get {
                return ResourceManager.GetString("NotificationPeriodNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers Only.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password not matched.
        /// </summary>
        public static string PasswordConfirmMsg {
            get {
                return ResourceManager.GetString("PasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password not matched.
        /// </summary>
        public static string PasswordMismach {
            get {
                return ResourceManager.GetString("PasswordMismach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password min length 6 character and you must have small ,capital,number and special character.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Schedule Found.
        /// </summary>
        public static string PaymentScheduleFound {
            get {
                return ResourceManager.GetString("PaymentScheduleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ther is payment founded ,are you sure you want delete it?.
        /// </summary>
        public static string PaymentScheduleFoundMsg {
            get {
                return ResourceManager.GetString("PaymentScheduleFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage between 1-100.
        /// </summary>
        public static string PercentageValueNotValid {
            get {
                return ResourceManager.GetString("PercentageValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers Only.
        /// </summary>
        public static string QtyNotNumber {
            get {
                return ResourceManager.GetString("QtyNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate must be number.
        /// </summary>
        public static string RateNotNumber {
            get {
                return ResourceManager.GetString("RateNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond type not exist.
        /// </summary>
        public static string RceBondTypeNotExist {
            get {
                return ResourceManager.GetString("RceBondTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required *.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit  Required *.
        /// </summary>
        public static string RequiredCredit {
            get {
                return ResourceManager.GetString("RequiredCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Required*.
        /// </summary>
        public static string RequiredDebit {
            get {
                return ResourceManager.GetString("RequiredDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter {0}.
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. 15 digits number..
        /// </summary>
        public static string SizeValueNotValid {
            get {
                return ResourceManager.GetString("SizeValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter start repetition date.
        /// </summary>
        public static string StartDateNotExistResource {
            get {
                return ResourceManager.GetString("StartDateNotExistResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select tax period .
        /// </summary>
        public static string TaxesPeriodNotExist {
            get {
                return ResourceManager.GetString("TaxesPeriodNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credit and debit must be equal.
        /// </summary>
        public static string TotalDebitNotEqualTotalCredit {
            get {
                return ResourceManager.GetString("TotalDebitNotEqualTotalCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized User .
        /// </summary>
        public static string UnauthorizedUserMessage {
            get {
                return ResourceManager.GetString("UnauthorizedUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown estimate budget.
        /// </summary>
        public static string UnknownEstimate {
            get {
                return ResourceManager.GetString("UnknownEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid website.
        /// </summary>
        public static string UrlNotValid {
            get {
                return ResourceManager.GetString("UrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name,user name can have character and numbers only.
        /// </summary>
        public static string UserNameValidation {
            get {
                return ResourceManager.GetString("UserNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least one role.
        /// </summary>
        public static string UserOrRoleNotExist {
            get {
                return ResourceManager.GetString("UserOrRoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Documents.
        /// </summary>
        public static string ViewDocument {
            get {
                return ResourceManager.GetString("ViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Financial Offers.
        /// </summary>
        public static string ViewFinancialOffer {
            get {
                return ResourceManager.GetString("ViewFinancialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Furniture Quote.
        /// </summary>
        public static string ViewFurnitureQuote {
            get {
                return ResourceManager.GetString("ViewFurnitureQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait ....
        /// </summary>
        public static string Waitingmsg {
            get {
                return ResourceManager.GetString("Waitingmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces not allowed.
        /// </summary>
        public static string WhiteSpaceNotAllowed {
            get {
                return ResourceManager.GetString("WhiteSpaceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number equal to or bigger than 0.
        /// </summary>
        public static string ZeroQuantity {
            get {
                return ResourceManager.GetString("ZeroQuantity", resourceCulture);
            }
        }
    }
}
